layout_spectrum: 0.5769082308339305
typography_spectrum: 0.19318958713110573
color:
  brandStrength: 0.9621563165332421
  lightness: 0.947220330210126
  saturation: 0.9006394515293512
  rhythmicContrast: 0.3666773713368111
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: abc.. to xyz
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa933a03-65dc-48ee-9d85-d195caeb51bc.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa933a03-65dc-48ee-9d85-d195caeb51bc.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: want forms ?
description: forms are good.. orders are good..
github: true
url: 'http://forms.abc-xyz.us/'
purpose:
  - type: external
    url: 'https://abc-xyz.us'
    label: abc.. to xyz
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a95e49dc-13f8-4a69-9c65-a1e0b3d6359c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/446d761f-a8e4-4def-a8f0-583c250beb33.png
